#!/bin/sh
[ -f /etc/adsbcot/.defaults_applied ] && exit 0

uci -q batch <<'EOF'
set dump1090.main=dump1090
set dump1090.main.enabled='1'
set dump1090.main.disabled='0'
set dump1090.main.net_only='0'
set dump1090.main.net='1'
set dump1090.main.net_sbs_port='30003'
set dump1090.main.net_bo_port='30005'
set dump1090.main.device_index='0'
set dump1090.main.gain='max'
set dump1090.main.write_json='/var/run/dump1090'
set dump1090.main.write_json_every='1'
delete dump1090.main.html_dir
commit dump1090
EOF

/etc/init.d/dump1090 enable
/etc/init.d/dump1090 restart

/etc/init.d/adsbcot enable
/etc/init.d/adsbcot restart

touch /etc/adsbcot/.defaults_applied
exit 0